#!/bin/sh

echo "Packaging Project"
cd  /home/mapr/Components/clickstream/tools/
mvn package > /home/mapr/logs/mvnRun
grep "BUILD SUCCESS" /home/mapr/logs/mvnRun > /home/mapr/logs/mvnResponse
#checkmvnResponse()

if [ -n $mvnResponse ]
then
	echo "Congratulations! mvn packaging successful. Proceeding further.."
	cd /home/mapr/Components/clickstream/dist/target/clickstream-1.3-SNAPSHOT
	echo `pwd`
	echo "Copying Jar"
	cp /home/mapr/Components/clickstream/tools/target/clickstream-tools-1.3-SNAPSHOT.jar  ./lib/
	cp /home/mapr/Components/clickstream/common/target/clickstream-common-1.3-SNAPSHOT.jar /home/mapr/Components/clickstream/dist/target/clickstream-1.3-SNAPSHOT/lib/
	echo "Starting Hbase Bulk Load Job"
	bin/cs hbasebulk -conf /home/mapr/Components/clickstream/dist/target/clickstream-1.3-SNAPSHOT/conf -database flightdemo -D clickstream.map.tasks.max=1900 1> /home/mapr/logs/hbaseBulkLoad.out 2> /home/mapr/logs/hbaseBulkLoad.err
	echo "Hbase Bulk Load Complated Successfully..Relax Now..:D"
else
	echo "mvn build failed!! Please check the cloned code."
	exit 1
fi



